version: "3.4"
services:
    transfer:
      restart: always
      build:
        context: ./
      ports:
        - 8060:8060    
    mysql:
      restart: always
      image: mysql:5.7.34
      environment:
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - ./mysql/data/:/var/lib/mysql/     
        - ./mysql/my.cnf:/etc/mysql/my.cnf    
        - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  
      ports:
        - 3306:3306    
    redis:
      restart: always
      image: redis:latest
      ports:
        - 127.0.0.1:6379:6379      
